### ISSUE TITLE
中文locale下无法显示

### ISSUE THREAD

**Issue by heddxh** [zhxie/Ikachan#1]
如果选择语言为中文，只有：
![image](https://github.com/zhxie/Ikachan/assets/63106571/4c764ac8-5cd8-4197-bdb4-53f0952f930e)

英文日文是正常的

**Comment by zhxie** [comment]
我这边试过是正常的，鱿鱼酱不会因为显示语言的不同产生不同的行为。
不过鱿鱼酱目前还不支持2023冬Chill Season更新。

**Comment by heddxh** [comment]
![image](https://github.com/zhxie/Ikachan/assets/63106571/e568a871-eacd-43b1-a6ff-70dca0339cbd)
![image](https://github.com/zhxie/Ikachan/assets/63106571/b9025239-cc76-4be8-93da-afe0e88944f8)
我倾向于是Apple的锅（
Anyway, thanks for developing this app!
